/**
 * ============================================================
 *  ALWAYS BE MINE - Configuration
 *  Change the theme and modes below to adapt for ANY occasion.
 *
 *  Themes:    "valentine" | "birthday" | "anniversary" | "confession"
 *  Modes:     Array of active modes (shown in nav)
 *             "proposal"  - Yes/No button interaction
 *             "timeline"  - Relationship milestone journey
 *             "letter"    - Typewriter love letter
 *             "quiz"      - How well do you know me?
 *             "jar"       - Reasons I love you jar
 *             "gallery"   - Photo memory lane
 *             "promises"  - Interactive promise builder
 *             "playlist"  - Embedded love songs playlist
 * ============================================================
 */

const theme = "valentine";

const themes = {
  valentine: {
    title: "Wanna Be My Valentine? ❤️",
    navTitle: "Our Love Story",
    heroName: "My Love",
    togetherSince: "2024-01-01",

    // Which modes to show (order = nav order)
    modes: ["proposal", "timeline", "letter", "quiz", "jar", "gallery", "promises", "playlist"],

    // --- Proposal Mode ---
    heading: "Will you be my Valentine?",
    acceptBtn: "Yes",
    acceptColor: "bg-green-500 hover:bg-green-600 active:bg-green-700",
    rejectColor: "bg-rose-500 hover:bg-rose-600 active:bg-rose-700",
    selectionColor: "selection:bg-rose-600 selection:text-white",
    marqueeMessages: [
      "You light up my world like no one else.",
      "Every moment with you feels like magic.",
      "My world begins and ends with you in it.",
      "You're the reason my heart beats faster.",
      "Life feels complete when you're around.",
      "I can't imagine my future without you.",
      "You're my sunshine on the darkest days.",
      "With you, every day is a blessing.",
      "You're the missing piece that completes my heart.",
      "You make even ordinary moments feel extraordinary.",
      "You make my world brighter and happier.",
      "You're the dream I never want to wake up from.",
      "Will you be the love of my life forever?",
    ],
    noPhrases: [
      "No", "Are you sure?", "Really sure?", "Think again!", "Last chance!",
      "Surely not?", "You might regret this!", "Give it another thought!",
      "Are you absolutely certain?", "This could be a mistake!",
      "U Have a heart! 💕", "Don't be so cold!", "Wouldn't you reconsider?",
      "Is that your final answer?", "You're breaking my heart ;(",
      "But... why? 😢", "Please, pretty please? 💖", "I can't take this! 😫",
      "Are you sure you want to do this to me? 😢",
      "You're gonna hurt my feelings! 😥",
      "I need you to reconsider, like now! 😓",
      "I believe in you, don't disappoint me! 💔",
      "My heart says yes, what about yours? ❤️",
      "Don't leave me hanging! 😬",
      "Plsss? :( You're breaking my heart 💔",
    ],
    yesTitle: "I Love You !!!",
    yesSubtitle: "You're the love of my life.",
    earlyPopup:
      "I love you sooo Much!!! ❤️, You've stolen my heart completely!!! 🥰💖 But itni pyaari ladki aur itni jaldi haan? Thoda aur nakhre karke mujhe tarpaao na! 🥰✨",
    latePopup:
      "I love you so much!! ❤️ You are my everything, my joy, my forever. Every moment with you is a memory I'll cherish forever, and my heart beats only for you.</br> Will you be the love of my life forever?",
    stubbornPopup:
      "My love for you is endless, like the stars in the sky—shining for you every night, even if you don't always notice. 🌟 I'll wait patiently, proving every day that you're my everything. ❤️ Please press 'Yes' and let's make this a forever story. 🥰✨<br/>'True love never gives up; it grows stronger with time.'",
    popupColor: "#716add",
    mouseStealerRange: [16, 25],
    stubbornCount: 25,

    // --- Timeline Mode ---
    timeline: [
      { date: "Jan 1, 2024", title: "First Met", description: "The day everything changed. I saw you and knew my life would never be the same.", emoji: "✨" },
      { date: "Feb 14, 2024", title: "First Valentine's", description: "Our first Valentine's together. I was so nervous, but you made everything feel perfect.", emoji: "💝" },
      { date: "Mar 20, 2024", title: "First Date", description: "That café, those laughs, the way time stopped when our hands touched.", emoji: "☕" },
      { date: "Jun 15, 2024", title: "Our First Trip", description: "Exploring new places with you felt like discovering a whole new world.", emoji: "✈️" },
      { date: "Aug 12, 2024", title: "Said 'I Love You'", description: "Three little words that meant everything. My heart still races thinking about it.", emoji: "❤️" },
      { date: "Dec 31, 2024", title: "New Year's Together", description: "Kissing you at midnight while fireworks lit up the sky. Perfect.", emoji: "🎆" },
      { date: "Today", title: "This Moment", description: "Right here, right now, I know there's no one else I'd rather have by my side.", emoji: "💕" },
    ],

    // --- Letter Mode ---
    letter: {
      greeting: "My Dearest Love,",
      paragraphs: [
        "I've been trying to find the right words to tell you how I feel, but every time I look at you, my heart does that thing again — the one where it forgets how to beat for a second.",
        "You came into my life when I least expected it, and somehow you became the most important part of it. Every laugh, every late-night conversation, every quiet moment — they all mean the world to me.",
        "I love the way you smile when you're trying not to. I love how you make even the boring stuff feel like an adventure. I love that you're you, exactly as you are.",
        "I don't know what the future holds, but I know this: I want every part of it to include you. You're my today, my tomorrow, and every day after that.",
      ],
      closing: "Forever and always yours,",
      signature: "— Swift",
    },

    // --- Quiz Mode ---
    quiz: [
      { q: "Where did we first meet?", options: ["At a café", "Online", "At a party", "Through friends"], answer: 1 },
      { q: "What's my favorite thing about you?", options: ["Your smile", "Your laugh", "Your kindness", "All of the above"], answer: 3 },
      { q: "What song reminds me of us?", options: ["Perfect - Ed Sheeran", "All of Me - John Legend", "At Last - Etta James", "A Thousand Years"], answer: 0 },
      { q: "What's our couple nickname?", options: ["Lovebirds", "Peanut Butter & Jelly", "Sunshine & Moonlight", "We don't have one"], answer: 2 },
      { q: "What's my dream for us?", options: ["Travel the world", "Build a home together", "Grow old side by side", "All of the above"], answer: 3 },
      { q: "When did I know you were special?", options: ["First conversation", "First date", "First fight (and making up)", "I've always known"], answer: 3 },
      { q: "What's my favorite memory of us?", options: ["Our first kiss", "That rainy day indoors", "Our first trip", "Every single day"], answer: 3 },
      { q: "What do I want for our future?", options: ["Adventures everywhere", "A cozy home with pets", "A lifetime of love", "All of it with you"], answer: 3 },
    ],
    quizResults: {
      low: "Hmm, we need more adventures together! But don't worry, I love teaching you about us. 💕",
      mid: "You know us pretty well! I'm impressed. But there's so much more to discover together. 💖",
      high: "You know my heart inside and out! I'm the luckiest person alive. 🥰",
      perfect: "PERFECT SCORE! You truly know everything about us. I love you endlessly! 💝✨",
    },

    // --- Reasons Jar ---
    reasons: [
      "Your smile lights up the darkest rooms",
      "You make ordinary moments feel magical",
      "The way you laugh at my terrible jokes",
      "How you always know when I need a hug",
      "Your kindness towards everyone around you",
      "The way your eyes sparkle when you're happy",
      "How you make me want to be a better person",
      "Your courage in facing everything life throws at you",
      "The way you love so deeply and completely",
      "How you remember the little things that matter",
      "Your infectious energy and passion for life",
      "The way you comfort me when I'm down",
      "How you make every day feel like a gift",
      "Your beautiful mind and the way you think",
      "The way you look at me when you think I'm not watching",
      "How you turn even boring errands into fun adventures",
      "Your incredible strength and resilience",
      "The way you make me feel safe and loved",
      "How you believe in me even when I don't",
      "Just the way you are — perfectly you",
    ],

    // --- Gallery Mode ---
    gallery: [
      { caption: "Standing together at sunset", src: "/gallery_couple_sunset.png", color: "from-orange-400 to-rose-500" },
      { caption: "A magical day in the park", src: "/gallery_couple_park.png", color: "from-emerald-400 to-teal-500" },
      { caption: "The day we first smiled at each other", src: "/gallery_cartoon_1.png", color: "from-rose-400 to-pink-500" },
      { caption: "Our first adventure together", src: "/gallery_cartoon_2.png", color: "from-purple-400 to-indigo-500" },
      { caption: "A romantic boat ride under the stars", src: "/gallery_boat.png", color: "from-blue-500 to-purple-600" },
      { caption: "Dancing with fireflies", src: "/gallery_dancing.png", color: "from-indigo-500 to-violet-600" },
      { caption: "Sharing ice cream on a sunny day", src: "/gallery_icecream.png", color: "from-pink-400 to-rose-500" },
      { caption: "Winter wonderland walk", src: "/gallery_winter.png", color: "from-cyan-400 to-blue-500" },
      { caption: "Lost in a magical library", src: "/gallery_library.png", color: "from-amber-400 to-orange-500" },
      { caption: "Coffee dates are the best", src: "/gallery_cafe.png", color: "from-orange-400 to-red-500" },
      { caption: "Making friends with enchanted animals", src: "/gallery_animals.png", color: "from-green-400 to-emerald-500" },
      { caption: "Exploring the sci-fi future", src: "/gallery_scifi.png", color: "from-fuchsia-500 to-pink-600" },
    ],

    // --- Promises Mode ---
    promises: [
      "I promise to always hold your hand, even when our hands are old and wrinkled.",
      "I promise to be your biggest fan, your safest place, and your home.",
      "I promise to never go to bed angry — I'll stay up and fight with you.",
      "I promise to always make you laugh, even on the hardest days.",
      "I promise to choose you, every single day, for the rest of my life.",
      "I promise to listen — really listen — even when the story is long.",
      "I promise to protect your dreams as fiercely as I protect my own.",
      "I promise to never stop dating you, even after we're old.",
      "I promise to love you when it's easy, and even more when it's hard.",
      "I promise that no matter what happens, my heart will always be yours.",
    ],
    promiseTitle: "My Promises to You",
    promiseSubtitle: "Click a card to flip and read each promise",

    // --- Playlist Mode ---
    playlist: {
      title: "Our Love Songs",
      subtitle: "Songs that remind me of us",
      spotify: "https://open.spotify.com/embed/playlist/37i9dQZF1DX5xJoc6fOBqA?utm_source=generator&theme=0",
      youtube: "https://www.youtube.com/embed/videoseries?list=PLrAXtmErZgOeiKm4sgNOknGvNjby9efdf",
      height: 352,
      compactHeight: 152,
      note: "Press play and let these songs set the mood for our story",
      tracks: [
        { title: "Perfect (Instrumental)", artist: "Romantic", src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3" },
        { title: "All of Me", artist: "Piano Cover", src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3" },
        { title: "At Last", artist: "Jazz Vibes", src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3" },
        { title: "A Thousand Years", artist: "Acoustic", src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3" },
        { title: "Thinking Out Loud", artist: "Guitar Cover", src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3" },
        { title: "Can't Help Falling in Love", artist: "Lofi", src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3" },
        { title: "Say You Won't Let Go", artist: "Acoustic Pop", src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3" },
        { title: "You Are The Reason", artist: "Piano & Cello", src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3" },
        { title: "Beautiful In White", artist: "Wedding Version", src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3" },
        { title: "Photograph", artist: "Instrumental", src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3" },
      ],
    },
  },

  birthday: {
    title: "Happy Birthday! 🎂🎉",
    navTitle: "Birthday Celebration",
    heroName: "Birthday Star",
    togetherSince: "2000-01-01",
    modes: ["proposal", "timeline", "letter", "quiz", "jar", "gallery", "playlist"],
    heading: "Make a Wish! 🎂",
    acceptBtn: "Let's Party! 🎉",
    acceptColor: "bg-purple-500 hover:bg-purple-600 active:bg-purple-700",
    rejectColor: "bg-amber-500 hover:bg-amber-600 active:bg-amber-700",
    selectionColor: "selection:bg-purple-600 selection:text-white",
    marqueeMessages: [
      "Today is all about YOU! 🎂", "Wishing you the happiest birthday ever!",
      "May all your dreams come true this year!", "You deserve the world and more! 🎁",
      "Another year of being absolutely amazing!", "Let's celebrate YOU today! 🥳",
      "Here's to another year of greatness!", "You make the world a brighter place! ✨",
      "Cheers to you on your special day! 🥂", "May this year bring you endless joy!",
    ],
    noPhrases: [
      "Wait, it's your birthday!", "Are you serious right now?",
      "You can't say no to cake! 🎂", "Think about the presents! 🎁",
      "The party can't start without you!", "Don't be like that, it's YOUR day!",
      "Come on, even a little smile? 😄", "The candles are waiting! 🕯️",
      "You're breaking the birthday spirit!", "Fine, more cake for me then! 😋",
      "But... what about the surprise?! 🎉", "I spent hours planning this! 🥺",
      "At least blow out the candles! 🕯️", "Birthday wishes are mandatory! ✨",
      "You're supposed to make a WISH! 💫", "Okay but you still look amazing today!",
      "The confetti is already everywhere! 🎊", "Everyone's waiting for your speech! 🎤",
      "Just press the button already! 😤", "Last chance before I eat your cake! 🍰",
    ],
    yesTitle: "Happy Birthday! 🎉🎂",
    yesSubtitle: "Here's to an incredible year ahead!",
    earlyPopup: "YAY! 🎉🎂 Happy Birthday! You deserve ALL the happiness in the world! Time to celebrate YOU! 🥳🎁",
    latePopup: "HAPPY BIRTHDAY!! 🎉🎂🥳 May this year bring you everything you've wished for and more! You're absolutely incredible and the world is lucky to have you! 💫✨",
    stubbornPopup: "Hey! It's YOUR birthday! 🎂 The least you can do is celebrate! Press the button and let's have the BEST party ever! 🎉🥳🎈",
    popupColor: "#7c3aed",
    mouseStealerRange: [12, 20],
    stubbornCount: 20,
    timeline: [
      { date: "The Day You Were Born", title: "A Star Was Born", description: "The world became a brighter place the moment you arrived.", emoji: "⭐" },
      { date: "Age 5", title: "Little Dreamer", description: "Already spreading joy and laughter to everyone around you.", emoji: "🌈" },
      { date: "Age 13", title: "Teenage Superstar", description: "Growing into the incredible person you were always meant to be.", emoji: "🎸" },
      { date: "Age 18", title: "Adulting Begins", description: "Ready to take on the world, one adventure at a time.", emoji: "🎓" },
      { date: "Today", title: "Another Year of Awesome", description: "Here's to celebrating every beautiful thing that makes you, YOU.", emoji: "🎂" },
    ],
    letter: {
      greeting: "Happy Birthday, Beautiful Soul!",
      paragraphs: [
        "Today the world celebrates something truly special — YOU. And honestly, I can't think of anyone who deserves to be celebrated more.",
        "Every year you grow more amazing, more inspiring, more YOU. Your smile, your laugh, your kindness — they make this world a better place every single day.",
        "I hope this year brings you everything your heart desires. More adventures, more joy, more of those moments that make life worth living.",
        "Thank you for being born. Thank you for being you. Thank you for letting me be part of your incredible story.",
      ],
      closing: "With all my love,",
      signature: "— Swift",
    },
    quiz: [
      { q: "What's my wish for your birthday?", options: ["Happiness forever", "World peace", "Unlimited cake", "All of the above"], answer: 3 },
      { q: "What should we do to celebrate?", options: ["Party all night", "Quiet dinner", "Adventure trip", "You choose!"], answer: 3 },
      { q: "What's the best gift I could give you?", options: ["Something expensive", "Handmade & heartfelt", "Experience-based", "Your presence is the gift"], answer: 3 },
      { q: "What's your birthday superpower?", options: ["Making everyone smile", "Being endlessly kind", "Spreading joy everywhere", "All of the above"], answer: 3 },
      { q: "How old do you feel today?", options: ["18 forever!", "Age is just a number", "Wiser than ever", "Young at heart"], answer: 3 },
    ],
    quizResults: {
      low: "Hmm, but that's okay! The birthday magic will fill in the gaps! 🎂",
      mid: "Not bad! You know yourself well. Happy birthday, superstar! 🎉",
      high: "Impressive! You really GET yourself. That's a superpower! 🌟",
      perfect: "PERFECT! You know yourself perfectly. That's the best gift! 🎁✨",
    },
    reasons: [
      "The way your eyes light up when you smile",
      "How you make everyone feel special",
      "Your incredible sense of humor",
      "The kindness you show to strangers",
      "How you chase your dreams fearlessly",
      "Your ability to find joy in small things",
      "The warmth of your hug",
      "How you light up every room you enter",
      "Your beautiful, beautiful soul",
      "The fact that you were born — the world is better for it",
    ],
    gallery: [
      { caption: "The day the world got brighter", color: "from-purple-400 to-pink-500" },
      { caption: "Growing up gorgeous", color: "from-amber-400 to-rose-500" },
      { caption: "Adventures and memories", color: "from-cyan-400 to-blue-500" },
      { caption: "Making every moment count", color: "from-green-400 to-teal-500" },
      { caption: "Pure joy, pure you", color: "from-fuchsia-400 to-violet-500" },
    ],
    promises: [
      "I promise to make your birthday as special as you make every day for me.",
      "I promise to always celebrate you — not just today, but every day.",
      "I promise to be the reason you smile at least once a day.",
      "I promise to always surprise you with love and joy.",
      "I promise to remind you how amazing you are whenever you forget.",
      "I promise to always be your biggest cheerleader.",
      "I promise to make this your best year yet.",
      "I promise to love you more with every passing year.",
    ],
    promiseTitle: "Birthday Promises to You",
    promiseSubtitle: "Click to flip and read each promise",

    // --- Playlist Mode ---
    playlist: {
      title: "Birthday Vibes",
      subtitle: "Songs to celebrate your special day",
      spotify: "https://open.spotify.com/embed/playlist/37i9dQZF1DWUVpAXiEPK8P?utm_source=generator&theme=0",
      youtube: "https://www.youtube.com/embed/videoseries?list=PLrAXtmErZgOeiKm4sgNOknGvNjby9efdf",
      height: 352,
      compactHeight: 152,
      note: "Turn up the volume and let's celebrate!",
      tracks: [
        { title: "Happy", artist: "Pharrell Williams", url: "https://open.spotify.com/track/60bWsV3kCwqh3g6b611aFh" },
        { title: "Birthday", artist: "Katy Perry", url: "https://open.spotify.com/track/60bWsV3kCwqh3g6b611aFh" },
        { title: "Celebrate", artist: "Mika", url: "https://open.spotify.com/track/0E7KjCF4f0IzMq2NMc0hHd" },
        { title: "Best Day of My Life", artist: "American Authors", url: "https://open.spotify.com/track/2yQ9m3EF5t5dTe6mRbP6lA" },
        { title: "Good As Hell", artist: "Lizzo", url: "https://open.spotify.com/track/5GhZPrCEmPNJmqrJ3bDPf" },
        { title: "Levitating", artist: "Dua Lipa", url: "https://open.spotify.com/track/39LLxExYz6ewLAo9BKLRX8" },
        { title: "Dynamite", artist: "BTS", url: "https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b" },
        { title: "Uptown Funk", artist: "Bruno Mars", url: "https://open.spotify.com/track/32OlwWuMpZ6b0aN2RZOeMS" },
      ],
    },
  },

  anniversary: {
    title: "Happy Anniversary! 💑",
    navTitle: "Our Journey Together",
    heroName: "My Everything",
    togetherSince: "2024-01-01",
    modes: ["proposal", "timeline", "letter", "quiz", "jar", "gallery", "promises"],
    heading: "Here's to Us! 💑",
    acceptBtn: "I Love You! ❤️",
    acceptColor: "bg-red-500 hover:bg-red-600 active:bg-red-700",
    rejectColor: "bg-pink-400 hover:bg-pink-500 active:bg-pink-600",
    selectionColor: "selection:bg-red-600 selection:text-white",
    marqueeMessages: [
      "Every day with you is a gift. 🎁", "You're my favorite adventure.",
      "I'd choose you again and again.", "You make forever feel too short.",
      "Here's to a lifetime more together!", "You're my person, always. 💕",
      "Falling in love with you was easy.", "You're my today and all of my tomorrows.",
      "The best thing that ever happened to me.", "I love growing old with you.",
    ],
    noPhrases: [
      "Wait, what?!", "After everything we've been through?!", "I'm giving you another chance! 😤",
      "Think of all our memories! 💭", "You can't be serious!", "But we're perfect together!",
      "I have a whole speech prepared! 🎤", "Our song is literally playing! 🎵",
      "Look at our photos! 📸", "You're killing me here!", "Our families are watching! 👀",
      "I planned a whole celebration! 🎊", "Not even for our anniversary?! 🥺",
      "This is NOT how I planned this! 😅", "At least pretend to be happy! 😄",
      "I promise the gift is worth it! 🎁", "Fine, I'll just cry then 😢",
      "You're ruining my moment! 💔", "One more chance? Pretty please? 🥺",
      "I swear it gets better! Trust me!",
    ],
    yesTitle: "Happy Anniversary! 💕",
    yesSubtitle: "Here's to many more beautiful years together.",
    earlyPopup: "Happy Anniversary, my love! 💕 Every moment with you is a treasure. Here's to forever and always! 💑✨",
    latePopup: "Happy Anniversary! 💕 You are my rock, my joy, my everything. I can't wait for all the years still to come with you. I love you endlessly! ❤️🥰",
    stubbornPopup: "Hey! Our anniversary deserves a celebration! 💑 Press 'Yes' and let me show you how much you mean to me. Every day with you is worth celebrating! 🥰✨",
    popupColor: "#dc2626",
    mouseStealerRange: [14, 22],
    stubbornCount: 22,
    timeline: [
      { date: "Day 1", title: "The Beginning", description: "Where our story started — the first page of the most beautiful book.", emoji: "📖" },
      { date: "Month 1", title: "Falling Deeper", description: "Every day I discovered something new to love about you.", emoji: "🌊" },
      { date: "Month 6", title: "Our Rhythm", description: "We found our groove — laughing, loving, living in perfect sync.", emoji: "🎵" },
      { date: "Year 1", title: "First Anniversary", description: "365 days of love, and I'd relive every single one.", emoji: "🎂" },
      { date: "Year 2", title: "Stronger Than Ever", description: "We've weathered storms and danced in the rain together.", emoji: "🌈" },
      { date: "Today", title: "Still Falling", description: "After all this time, my heart still skips a beat when I see you.", emoji: "💕" },
    ],
    letter: {
      greeting: "To My Forever Person,",
      paragraphs: [
        "Another year of us. Another 365 reasons why loving you is the easiest thing I've ever done.",
        "Remember when we were just two people figuring things out? Now look at us — a love story that I'd read over and over again. Every chapter better than the last.",
        "You've seen me at my best and my worst, and you chose to stay. That kind of love is rare, and I will never take it for granted.",
        "Here's to every morning I get to wake up next to you, every argument that makes us stronger, and every quiet moment that reminds me why I fell in love.",
      ],
      closing: "With all that I am,",
      signature: "— Forever yours",
    },
    quiz: [
      { q: "How long have we been together?", options: ["Feels like forever (in the best way)", "Too short, never enough", "Every day counts", "Time flies when I'm with you"], answer: 3 },
      { q: "What's the secret to our love?", options: ["Communication", "Laughter", "Choosing each other daily", "All of the above"], answer: 3 },
      { q: "What's our love language?", options: ["Quality time", "Words of affirmation", "Physical touch", "All of them with you"], answer: 3 },
      { q: "Where do you see us in 10 years?", options: ["Still adventuring", "Growing old together", "Still laughing daily", "All of the above"], answer: 3 },
      { q: "What's the best part of us?", options: ["How we communicate", "How we laugh together", "How we grow together", "Everything about us"], answer: 3 },
    ],
    quizResults: {
      low: "We have so many more memories to make! This is just the beginning. 💕",
      mid: "You know us well! But the best is yet to come. 💖",
      high: "You know our love inside and out. My heart is so full. 🥰",
      perfect: "PERFECT SCORE! You ARE our love story. I love you endlessly! 💝✨",
    },
    reasons: [
      "The way you hold me when the world is too much",
      "How you always make time for what matters",
      "Your patience when I'm difficult",
      "The way you look at me after all this time",
      "How you celebrate my wins like they're yours",
      "Your ability to make any place feel like home",
      "The way we can sit in silence and it's perfect",
      "How you challenge me to be better",
      "Your unwavering belief in us",
      "The way you love — wholly, deeply, beautifully",
    ],
    gallery: [
      { caption: "Where it all began", color: "from-rose-400 to-red-500" },
      { caption: "Our first adventure as us", color: "from-amber-400 to-orange-500" },
      { caption: "Falling deeper every day", color: "from-purple-400 to-indigo-500" },
      { caption: "Through every storm, together", color: "from-cyan-400 to-blue-500" },
      { caption: "Still choosing each other", color: "from-pink-400 to-rose-500" },
      { caption: "Forever and always", color: "from-fuchsia-400 to-pink-500" },
    ],
    promises: [
      "I promise to always hold your hand, even when our hands are old and wrinkled.",
      "I promise to be your biggest fan, your safest place, and your home.",
      "I promise to never go to bed angry — I'll stay up and fight with you.",
      "I promise to always make you laugh, even on the hardest days.",
      "I promise to choose you, every single day, for the rest of my life.",
      "I promise to listen — really listen — even when the story is long.",
      "I promise to protect your dreams as fiercely as I protect my own.",
      "I promise to never stop dating you, even after we're old.",
      "I promise to love you when it's easy, and even more when it's hard.",
      "I promise that no matter what happens, my heart will always be yours.",
    ],
    promiseTitle: "My Renewed Promises",
    promiseSubtitle: "Click a card to flip and read each promise",

    // --- Playlist Mode ---
    playlist: {
      title: "Our Anniversary Playlist",
      subtitle: "Songs from every chapter of us",
      spotify: "https://open.spotify.com/embed/playlist/37i9dQZF1DX08SipB0W7aE?utm_source=generator&theme=0",
      youtube: "https://www.youtube.com/embed/videoseries?list=PLrAXtmErZgOeiKm4sgNOknGvNjby9efdf",
      height: 352,
      compactHeight: 152,
      note: "Every song here reminds me of a moment we shared",
      tracks: [
        { title: "Perfect", artist: "Ed Sheeran", url: "https://open.spotify.com/track/0tgVpDi06FyKnA3Qy7zw4" },
        { title: "All of Me", artist: "John Legend", url: "https://open.spotify.com/track/3U4isOIWM3VvDubwSI3y7a" },
        { title: "At Last", artist: "Etta James", url: "https://open.spotify.com/track/4Hhv2vrOTy89HFRcjU3QOx" },
        { title: "Love Someone", artist: "Lukas Graham", url: "https://open.spotify.com/track/1F5Y1L1XvV6QeYk7x4a1cF" },
        { title: "Stay With Me", artist: "Sam Smith", url: "https://open.spotify.com/track/6lS8q48T1OaJrRH8U8gWw" },
        { title: "I'm Yours", artist: "Jason Mraz", url: "https://open.spotify.com/track/3COkNtTg26CM2Poj7WcYwc" },
        { title: "Make You Feel My Love", artist: "Adele", url: "https://open.spotify.com/track/3E8gQ0v0VFPkHYRQa49y3c" },
        { title: "I Don't Want to Miss a Thing", artist: "Aerosmith", url: "https://open.spotify.com/track/5EdeyY4wz0a7t5yVx2QnVl" },
      ],
    },
  },

  confession: {
    title: "I Have Something to Say... 💝",
    navTitle: "My Confession",
    heroName: "You",
    togetherSince: "2024-01-01",
    modes: ["proposal", "timeline", "letter", "quiz", "jar", "promises"],
    heading: "I Really Like You! 💝",
    acceptBtn: "Tell Me! 👀",
    acceptColor: "bg-violet-500 hover:bg-violet-600 active:bg-violet-700",
    rejectColor: "bg-slate-500 hover:bg-slate-600 active:bg-slate-700",
    selectionColor: "selection:bg-violet-600 selection:text-white",
    marqueeMessages: [
      "You've been on my mind a lot lately.", "I smile every time I see your name.",
      "You make ordinary days extraordinary.", "I just had to tell you how I feel.",
      "You're different from everyone else.", "My heart races when you're near.",
      "I can't keep this a secret anymore.", "You deserve to know how I feel.",
      "Every moment with you is special.", "I'm brave enough to say this: I like you.",
    ],
    noPhrases: [
      "Oh come on!", "Just hear me out! 😅", "I practiced this in the mirror!",
      "Give me a chance! 🥺", "You're making this really hard!",
      "I had a whole speech ready!", "My heart is literally shaking! 😰",
      "This took so much courage!", "At least let me finish! 😤",
      "I swear I'm worth it!", "Don't leave me on read! 📱",
      "I rehearsed this 50 times! 😂", "Fine, I'll just faint then! 😵",
      "This is scarier than I thought!", "You're making me sweat! 😅",
      "I'm literally shaking right now!", "One more chance to explain? 🥺",
      "My hands are trembling! 🫣", "I promise I'm not weird! ...mostly",
      "Just... please? 💜",
    ],
    yesTitle: "Thank You! 💜",
    yesSubtitle: "You just made my whole day. Maybe my whole year.",
    earlyPopup: "Wait really?! 🥺💜 You just made me the happiest person alive! I promise I'm worth getting to know! Let's start with a conversation? ✨",
    latePopup: "I can't believe you listened! 💜 You have no idea how much this means to me. I promise to make you smile every single day. This is just the beginning! 🥰",
    stubbornPopup: "I get it, this is unexpected! 😅 But I poured my heart into this. Just give me one chance to show you how much I care. Press 'Yes' and let's see where this goes! 💜✨",
    popupColor: "#7c3aed",
    mouseStealerRange: [10, 18],
    stubbornCount: 18,
    timeline: [
      { date: "First Saw You", title: "The Spark", description: "That moment when everything paused and my heart whispered 'them'.", emoji: "⚡" },
      { date: "First Conversation", title: "Butterflies", description: "My hands were shaking, but every word felt like magic.", emoji: "🦋" },
      { date: "Getting Closer", title: "Falling Quietly", description: "Every laugh, every glance — I was falling and I didn't want to stop.", emoji: "🌙" },
      { date: "The Decision", title: "Time to Be Brave", description: "I decided my feelings were too big to keep inside.", emoji: "💪" },
      { date: "Right Now", title: "This Moment", description: "Here I am, heart on my sleeve, hoping you'll give us a chance.", emoji: "💝" },
    ],
    letter: {
      greeting: "Dear You,",
      paragraphs: [
        "I've started writing this letter a hundred times. Each time, I delete it because no combination of words feels big enough for what I want to say.",
        "But today I'm being brave. Today I'm choosing honesty over fear, because you deserve to know that someone out there thinks you're absolutely incredible.",
        "I notice the little things about you — the way you tilt your head when you're thinking, how your whole face changes when you laugh, the kindness you show without even realizing it.",
        "I don't know what will happen after you read this. But I know that hiding how I feel isn't fair to either of us. So here it is, raw and real: I like you. A lot.",
      ],
      closing: "With all my courage,",
      signature: "— The one who likes you",
    },
    quiz: [
      { q: "What caught my attention first?", options: ["Your smile", "Your laugh", "Your eyes", "All of the above"], answer: 3 },
      { q: "How often do I think about you?", options: ["Sometimes", "Often", "All the time", "Literally every second"], answer: 3 },
      { q: "What would I do to spend time with you?", options: ["Anything", "Everything", "Whatever you want", "All of the above"], answer: 3 },
      { q: "How do I feel right now?", options: ["Nervous", "Excited", "Terrified", "All of the above, for you"], answer: 3 },
    ],
    quizResults: {
      low: "I'm still figuring you out, but that's the fun part! 💕",
      mid: "I notice more about you than you think! 👀",
      high: "I pay attention to every little thing about you. 🥰",
      perfect: "You're all I see, all I think about, all I want. 💜✨",
    },
    reasons: [
      "The way you make me laugh without even trying",
      "How you light up when you talk about something you love",
      "Your kindness to everyone around you",
      "The way my heart races when you're near",
      "How you make even silence feel comfortable",
      "Your incredible mind and the way you see the world",
      "The way you challenge me to think differently",
      "How you make ordinary moments feel extraordinary",
      "Just the way you are — perfectly, beautifully you",
      "Because liking you is the easiest thing I've ever done",
    ],
    promises: [
      "I promise to always be honest with you, even when it's scary.",
      "I promise to respect your feelings, whatever they may be.",
      "I promise to never pressure you — your comfort comes first.",
      "I promise to show you, not just tell you, how much I care.",
      "I promise to be patient and let things unfold naturally.",
      "I promise to always make you smile.",
      "I promise to be the person you can count on.",
      "I promise to never stop trying to make you happy.",
    ],
    promiseTitle: "My Promises If You Give Us a Chance",
    promiseSubtitle: "Click to flip and read each promise",

    // --- Playlist Mode ---
    playlist: {
      title: "Songs That Make Me Think of You",
      subtitle: "Every beat reminds me of your smile",
      spotify: "https://open.spotify.com/embed/playlist/37i9dQZF1DX5xJoc6fOBqA?utm_source=generator&theme=0",
      youtube: "https://www.youtube.com/embed/videoseries?list=PLrAXtmErZgOeiKm4sgNOknGvNjby9efdf",
      height: 352,
      compactHeight: 152,
      note: "Every song here was played on repeat while thinking about you",
      tracks: [
        { title: "Adore You", artist: "Harry Styles", url: "https://open.spotify.com/track/6UelhqQWMukV91IHlMPWkZ" },
        { title: "Crush", artist: "Tessa Violet", url: "https://open.spotify.com/track/5CQ3hWbIkA0ZoQb0JmUHJW" },
        { title: "Mine", artist: "Taylor Swift", url: "https://open.spotify.com/track/1JbJkBTk4p0sMN2f9YmM0P" },
        { title: "Just the Way You Are", artist: "Bruno Mars", url: "https://open.spotify.com/track/0bYg9bo5kfgSfHsLBS9Rvf" },
        { title: "What Makes You Beautiful", artist: "One Direction", url: "https://open.spotify.com/track/55iguSn8hQq8DMo6F09Bz" },
        { title: "Beautiful Things", artist: "Benson Boone", url: "https://open.spotify.com/track/01bQw8Bs10RHVcLhSM1j5N" },
        { title: "Birds of a Feather", artist: "Billie Eilish", url: "https://open.spotify.com/track/62LkHUWYQXoZP3q2aJn9mP" },
        { title: "Roses", artist: "The Chainsmokers", url: "https://open.spotify.com/track/4TUGhCrHV85sH66bVb1l3b" },
      ],
    },
  },
};

const config = themes[theme];

export default config;
