/**
 * ============================================================
 *  ALWAYS BE MINE - Configuration
 *  Change the theme below to adapt this for ANY occasion.
 *  Themes: "valentine" | "birthday" | "anniversary" | "confession"
 * ============================================================
 */

const theme = "valentine";

const themes = {
  valentine: {
    title: "Wanna Be My Valentine? ❤️",
    heading: "Will you be my Valentine?",
    acceptBtn: "Yes",
    acceptColor: "bg-green-500 hover:bg-green-600 active:bg-green-700",
    rejectColor: "bg-rose-500 hover:bg-rose-600 active:bg-rose-700",
    selectionColor: "selection:bg-rose-600 selection:text-white",
    marqueeMessages: [
      "You light up my world like no one else.",
      "Every moment with you feels like magic.",
      "My world begins and ends with you in it.",
      "You're the reason my heart beats faster.",
      "Life feels complete when you're around.",
      "I can't imagine my future without you.",
      "You're my sunshine on the darkest days.",
      "With you, every day is a blessing.",
      "You're the missing piece that completes my heart.",
      "You make even ordinary moments feel extraordinary.",
      "You make my world brighter and happier.",
      "You're the dream I never want to wake up from.",
      "Will you be the love of my life forever?",
    ],
    noPhrases: [
      "No",
      "Are you sure?",
      "Really sure?",
      "Think again!",
      "Last chance!",
      "Surely not?",
      "You might regret this!",
      "Give it another thought!",
      "Are you absolutely certain?",
      "This could be a mistake!",
      "U Have a heart! 💕",
      "Don't be so cold!",
      "Wouldn't you reconsider?",
      "Is that your final answer?",
      "You're breaking my heart ;(",
      "But... why? 😢",
      "Please, pretty please? 💖",
      "I can't take this! 😫",
      "Are you sure you want to do this to me? 😢",
      "You're gonna hurt my feelings! 😥",
      "I need you to reconsider, like now! 😓",
      "I believe in you, don't disappoint me! 💔",
      "My heart says yes, what about yours? ❤️",
      "Don't leave me hanging! 😬",
      "Plsss? :( You're breaking my heart 💔",
    ],
    yesTitle: "I Love You !!!",
    yesSubtitle: "You're the love of my life.",
    earlyPopup:
      "I love you sooo Much!!! ❤️, You've stolen my heart completely!!! 🥰💖 But itni pyaari ladki aur itni jaldi haan? Thoda aur nakhre karke mujhe tarpaao na! 🥰✨",
    latePopup:
      "I love you so much!! ❤️ You are my everything, my joy, my forever. Every moment with you is a memory I'll cherish forever, and my heart beats only for you.</br> Will you be the love of my life forever?",
    stubbornPopup:
      "My love for you is endless, like the stars in the sky—shining for you every night, even if you don't always notice. 🌟 I'll wait patiently, proving every day that you're my everything. ❤️ Please press 'Yes' and let's make this a forever story. 🥰✨<br/>'True love never gives up; it grows stronger with time.'",
    popupColor: "#716add",
    mouseStealerRange: [16, 25],
    stubbornCount: 25,
  },

  birthday: {
    title: "Happy Birthday! 🎂🎉",
    heading: "Make a Wish! 🎂",
    acceptBtn: "Let's Party! 🎉",
    acceptColor: "bg-purple-500 hover:bg-purple-600 active:bg-purple-700",
    rejectColor: "bg-amber-500 hover:bg-amber-600 active:bg-amber-700",
    selectionColor: "selection:bg-purple-600 selection:text-white",
    marqueeMessages: [
      "Today is all about YOU! 🎂",
      "Wishing you the happiest birthday ever!",
      "May all your dreams come true this year!",
      "You deserve the world and more! 🎁",
      "Another year of being absolutely amazing!",
      "Let's celebrate YOU today! 🥳",
      "Here's to another year of greatness!",
      "You make the world a brighter place! ✨",
      "Cheers to you on your special day! 🥂",
      "May this year bring you endless joy!",
    ],
    noPhrases: [
      "Wait, it's your birthday!",
      "Are you serious right now?",
      "You can't say no to cake! 🎂",
      "Think about the presents! 🎁",
      "The party can't start without you!",
      "Don't be like that, it's YOUR day!",
      "Come on, even a little smile? 😄",
      "The candles are waiting! 🕯️",
      "You're breaking the birthday spirit!",
      "Fine, more cake for me then! 😋",
      "But... what about the surprise?! 🎉",
      "I spent hours planning this! 🥺",
      "At least blow out the candles! 🕯️",
      "Birthday wishes are mandatory! ✨",
      "You're supposed to make a WISH! 💫",
      "Okay but you still look amazing today!",
      "The confetti is already everywhere! 🎊",
      "Everyone's waiting for your speech! 🎤",
      "Just press the button already! 😤",
      "Last chance before I eat your cake! 🍰",
    ],
    yesTitle: "Happy Birthday! 🎉🎂",
    yesSubtitle: "Here's to an incredible year ahead!",
    earlyPopup:
      "YAY! 🎉🎂 Happy Birthday! You deserve ALL the happiness in the world! Time to celebrate YOU! 🥳🎁",
    latePopup:
      "HAPPY BIRTHDAY!! 🎉🎂🥳 May this year bring you everything you've wished for and more! You're absolutely incredible and the world is lucky to have you! 💫✨",
    stubbornPopup:
      "Hey! It's YOUR birthday! 🎂 The least you can do is celebrate! Press the button and let's have the BEST party ever! 🎉🥳🎈",
    popupColor: "#7c3aed",
    mouseStealerRange: [12, 20],
    stubbornCount: 20,
  },

  anniversary: {
    title: "Happy Anniversary! 💑",
    heading: "Here's to Us! 💑",
    acceptBtn: "I Love You! ❤️",
    acceptColor: "bg-red-500 hover:bg-red-600 active:bg-red-700",
    rejectColor: "bg-pink-400 hover:bg-pink-500 active:bg-pink-600",
    selectionColor: "selection:bg-red-600 selection:text-white",
    marqueeMessages: [
      "Every day with you is a gift. 🎁",
      "You're my favorite adventure.",
      "I'd choose you again and again.",
      "You make forever feel too short.",
      "Here's to a lifetime more together!",
      "You're my person, always. 💕",
      "Falling in love with you was easy.",
      "You're my today and all of my tomorrows.",
      "The best thing that ever happened to me.",
      "I love growing old with you.",
    ],
    noPhrases: [
      "Wait, what?!",
      "After everything we've been through?!",
      "I'm giving you another chance! 😤",
      "Think of all our memories! 💭",
      "You can't be serious!",
      "But we're perfect together!",
      "I have a whole speech prepared! 🎤",
      "Our song is literally playing! 🎵",
      "Look at our photos! 📸",
      "You're killing me here!",
      "Our families are watching! 👀",
      "I planned a whole celebration! 🎊",
      "Not even for our anniversary?! 🥺",
      "This is NOT how I planned this! 😅",
      "At least pretend to be happy! 😄",
      "I promise the gift is worth it! 🎁",
      "Fine, I'll just cry then 😢",
      "You're ruining my moment! 💔",
      "One more chance? Pretty please? 🥺",
      "I swear it gets better! Trust me!",
    ],
    yesTitle: "Happy Anniversary! 💕",
    yesSubtitle: "Here's to many more beautiful years together.",
    earlyPopup:
      "Happy Anniversary, my love! 💕 Every moment with you is a treasure. Here's to forever and always! 💑✨",
    latePopup:
      "Happy Anniversary! 💕 You are my rock, my joy, my everything. I can't wait for all the years still to come with you. I love you endlessly! ❤️🥰",
    stubbornPopup:
      "Hey! Our anniversary deserves a celebration! 💑 Press 'Yes' and let me show you how much you mean to me. Every day with you is worth celebrating! 🥰✨",
    popupColor: "#dc2626",
    mouseStealerRange: [14, 22],
    stubbornCount: 22,
  },

  confession: {
    title: "I Have Something to Say... 💝",
    heading: "I Really Like You! 💝",
    acceptBtn: "Tell Me! 👀",
    acceptColor: "bg-violet-500 hover:bg-violet-600 active:bg-violet-700",
    rejectColor: "bg-slate-500 hover:bg-slate-600 active:bg-slate-700",
    selectionColor: "selection:bg-violet-600 selection:text-white",
    marqueeMessages: [
      "You've been on my mind a lot lately.",
      "I smile every time I see your name.",
      "You make ordinary days extraordinary.",
      "I just had to tell you how I feel.",
      "You're different from everyone else.",
      "My heart races when you're near.",
      "I can't keep this a secret anymore.",
      "You deserve to know how I feel.",
      "Every moment with you is special.",
      "I'm brave enough to say this: I like you.",
    ],
    noPhrases: [
      "Oh come on!",
      "Just hear me out! 😅",
      "I practiced this in the mirror!",
      "Give me a chance! 🥺",
      "You're making this really hard!",
      "I had a whole speech ready!",
      "My heart is literally shaking! 😰",
      "This took so much courage!",
      "At least let me finish! 😤",
      "I swear I'm worth it!",
      "Don't leave me on read! 📱",
      "I rehearsed this 50 times! 😂",
      "Fine, I'll just faint then! 😵",
      "This is scarier than I thought!",
      "You're making me sweat! 😅",
      "I'm literally shaking right now!",
      "One more chance to explain? 🥺",
      "My hands are trembling! 🫣",
      "I promise I'm not weird! ...mostly",
      "Just... please? 💜",
    ],
    yesTitle: "Thank You! 💜",
    yesSubtitle: "You just made my whole day. Maybe my whole year.",
    earlyPopup:
      "Wait really?! 🥺💜 You just made me the happiest person alive! I promise I'm worth getting to know! Let's start with a conversation? ✨",
    latePopup:
      "I can't believe you listened! 💜 You have no idea how much this means to me. I promise to make you smile every single day. This is just the beginning! 🥰",
    stubbornPopup:
      "I get it, this is unexpected! 😅 But I poured my heart into this. Just give me one chance to show you how much I care. Press 'Yes' and let's see where this goes! 💜✨",
    popupColor: "#7c3aed",
    mouseStealerRange: [10, 18],
    stubbornCount: 18,
  },
};

const config = themes[theme];

export default config;
